### ISSUE TITLE
Licensing Issues

### ISSUE THREAD

**Issue by Validark** [boatbomber/BoatTween#6]
Hello, and thank you for sharing this library with the community.

Most of this code is derivative from the work of others, and merely listing a username is generally not enough to satisfy the software licenses under which the original code was released. Further, in most cases the original author is not even mentioned. Please add Licenses and Copyright notices and attributions where applicable. (thanks to [LPGhatguy](https://github.com/LPGhatguy) for cueing me in to the importance of licenses)

- The `Bezier` library is derived from [gre/bezier-easing](https://github.com/gre/bezier-easing) (Copyright © 2014 Gaëtan Renaudeau, MIT License). If you got your port from [howmanysmall](https://github.com/howmanysmall), you are probably using a derivation of [my port](https://github.com/Validark/Roblox-TS-Libraries/tree/master/cubic-bezier) ([older release here](https://github.com/RoStrap/Interpolation/blob/master/Bezier.lua)). (Copyright © 2019 Validark, either ISC or MIT license is fine)

- The `Lerps` library was primarily derived from [Fraktality/anim](https://github.com/Fraktality/anim) (Copyright © 2017 Parker Stebbins <parker@fractality.io>, MIT License), and no doubt derived from [my library](https://github.com/Validark/Roblox-TS-Libraries/tree/master/lerp-functions)  as well ([older release here](https://github.com/RoStrap/Interpolation/blob/master/Lerps.lua)). (Copyright © 2019 Validark, either ISC or MIT license is fine)
  - The NumberSequence and Region3 Lerps were written by [Sharksie](https://www.roblox.com/users/4812582/profile) in 2016 (no license but original is [here](https://www.roblox.com/library/320968883))

- The `TweenFunctions` library is primarily derived from [Robert Penner's easing equations](http://robertpenner.com/easing/), released under the BSD License. (Copyright © 2001 Robert Penner, BSD License (please include a copy in the source) ) The Lua port is derived from [EmmanuelOga's easing library](https://github.com/EmmanuelOga/easing) (Copyright © 2010, Emmanuel Oga, MIT License) and [my modifications for the Roblox audience](https://github.com/Validark/Roblox-TS-Libraries/blob/master/easing-functions/init.lua) ([older release](https://github.com/RoStrap/Interpolation/blob/master/EasingFunctions.lua)) (Copyright © 2019 Validark, either ISC or MIT license is fine)
  - `RevBack` and `RidiculousWiggle` are by [Sharksie](https://www.roblox.com/users/4812582/profile) in 2016 (no license but original is [here](https://www.roblox.com/library/320968883), side note: there are a few more easing functions in the original that could be added to this library)
  - `Spring` and `SoftSpring` are from [lellowtide AKA YellowTide](https://www.roblox.com/users/16826035/profile)
  - Unfortunately, I don't know for certain who wrote `Smooth` and `Smoother`, but it might be the work of [ScriptOn](https://www.roblox.com/users/9843936/profile). Perhaps we should try to contact him?

Thank you in advance for respecting the work of others!

**Comment by boatbomber** [comment]
Thank you for bringing this to my attention!

**Comment by boatbomber** [comment]
Added a proper licenses file, and made it `.lua` so it'll remain inside the source when built to a `.rbxm`. Thanks again.

**Comment by Validark** [comment]
Haha, I don't think you need tons of copies of the MIT License. I think you can just have it once and above the MIT License just list the MIT Copyrights I compiled for you in this issue.

Other than that, it would be nice if some of the other developers behind this module, especially Fraktality, got a shout-out in the README and devforum post. Sharksie and YellowTide made contributions worth mentioning too, since without them you wouldn't have 32 Easing Styles. (And of course, thank Robert Penner for supplying the bulk!)

This library is the culmination of a lot of people's work over the years, and you should be proud of that! I don't know about you but I think it's really awesome that this library has a lineage and that each time the next person compiles a version of this library there are even more options, features, and styles to be found.
